export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_PENDING = "GET_USER_LIST_PENDING";
export const GET_USER_LIST_FULFILLED = "GET_USER_LIST_FULFILLED";
export const GET_USER_LIST_REJECTED = "GET_USER_LIST_REJECTED";

export const GET_POST_LIST = "GET_POST_LIST";
export const GET_POST_LIST_PENDING = "GET_POST_LIST_PENDING";
export const GET_POST_LIST_FULFILLED = "GET_POST_LIST_FULFILLED";
export const GET_POST_LIST_REJECTED = "GET_POST_LIST_REJECTED";

export const GET_COMMENTS_BY_POST_ID = "GET_COMMENTS_BY_POST_ID";
export const GET_COMMENTS_BY_POST_ID_PENDING =
  "GET_COMMENTS_BY_POST_ID_PENDING";
export const GET_COMMENTS_BY_POST_ID_FULFILLED =
  "GET_COMMENTS_BY_POST_ID_FULFILLED";
export const GET_COMMENTS_BY_POST_ID_REJECTED =
  "GET_COMMENTS_BY_POST_ID_REJECTED";

export const POST_REPLY = "POST_REPLY";
export const POST_REPLY_PENDING = "POST_REPLY_PENDING";
export const POST_REPLY_FULFILLED = "POST_REPLY_FULFILLED";
export const POST_REPLY_REJECTED = "POST_REPLY_REJECTED";

export const PUT_REPLY = "PUT_REPLY";
export const PUT_REPLY_PENDING = "PUT_REPLY_PENDING";
export const PUT_REPLY_FULFILLED = "PUT_REPLY_FULFILLED";
export const PUT_REPLY_REJECTED = "PUT_REPLY_REJECTED";
