export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_PENDING = "GET_USER_LIST_PENDING";
export const GET_USER_LIST_FULFILLED = "GET_USER_LIST_FULFILLED";
export const GET_USER_LIST_REJECTED = "GET_USER_LIST_REJECTED";
