export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_PENDING = "GET_USER_LIST_PENDING";
export const GET_USER_LIST_FULFILLED = "GET_USER_LIST_FULFILLED";
export const GET_USER_LIST_REJECTED = "GET_USER_LIST_REJECTED";

export const GET_POST_LIST = "GET_POST_LIST";
export const GET_POST_LIST_PENDING = "GET_POST_LIST_PENDING";
export const GET_POST_LIST_FULFILLED = "GET_POST_LIST_FULFILLED";
export const GET_POST_LIST_REJECTED = "GET_POST_LIST_REJECTED";
